[package]
name = "tokio-childstream"
version = "0.1.0"
authors = ["nathan <nathan+dev@electriccoin.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-core = "0.3.*"
futures-util = "0.3.*"
tokio = { version = "0.2.*", features = ["process", "io-util", "stream"] }

[dev-dependencies]
tokio = { version = "0.2.*", features = ["macros", "rt-core"] }
