[package]
name = "tokio-interval-stream"
version = "0.1.0"
homepage.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures.workspace = true
tokio = { workspace = true, features = ["time"] }
