[package]
name = "exoshell-event-queue"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
derive_more.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["sync", "rt"] }
