[package]
name = "exoshell-command"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
tokio-childstream.workspace = true
tokio = { workspace = true, features = ["process"] }
